# Generated by Django 2.2 on 2022-03-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWDapis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WellNo', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=19)),
                ('time', models.CharField(max_length=19)),
                ('WL_Well_Depth', models.CharField(max_length=5)),
                ('Ht_of_Ms_Pt', models.CharField(max_length=5)),
                ('Water_Level', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Remarks', models.CharField(max_length=5)),
                ('Flag', models.CharField(max_length=5)),
                ('Water_Level_MBMP', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
