# Generated by Django 2.2 on 2022-03-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWDapis', '0002_waterlevels'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WellNo', models.CharField(max_length=10)),
                ('SampleID', models.IntegerField()),
                ('SamplingDate', models.CharField(max_length=19)),
                ('AnalysisDate', models.CharField(max_length=5)),
                ('SamplingDepth', models.CharField(max_length=5)),
                ('LabID', models.CharField(max_length=5)),
                ('Colour', models.CharField(max_length=5)),
                ('Odour', models.CharField(max_length=5)),
                ('Turbidity', models.CharField(max_length=5)),
                ('Temp', models.CharField(max_length=5)),
                ('pH', models.CharField(max_length=7)),
                ('EC', models.CharField(max_length=5)),
                ('THard', models.CharField(max_length=8)),
                ('Alkalinity', models.CharField(max_length=8)),
                ('TDS', models.CharField(max_length=7)),
                ('CO3', models.CharField(max_length=6)),
                ('HCO3', models.CharField(max_length=8)),
                ('Cl', models.CharField(max_length=8)),
                ('SO4', models.CharField(max_length=6)),
                ('NO3', models.CharField(max_length=10)),
                ('Ca', models.CharField(max_length=8)),
                ('Mg', models.CharField(max_length=9)),
                ('Na', models.CharField(max_length=8)),
                ('K', models.CharField(max_length=8)),
                ('F', models.CharField(max_length=6)),
                ('Si', models.CharField(max_length=5)),
                ('As', models.CharField(max_length=5)),
                ('Alk_Phen', models.CharField(max_length=5)),
                ('BOD', models.CharField(max_length=5)),
                ('P_Total', models.CharField(max_length=5)),
                ('COD', models.CharField(max_length=5)),
                ('DO', models.CharField(max_length=5)),
                ('F_Coli', models.CharField(max_length=5)),
                ('Pesticide', models.CharField(max_length=5)),
                ('PO4', models.CharField(max_length=5)),
                ('Pb', models.CharField(max_length=5)),
                ('Cr', models.CharField(max_length=5)),
                ('Cd', models.CharField(max_length=5)),
                ('Mn', models.CharField(max_length=5)),
                ('Ni', models.CharField(max_length=5)),
                ('Fe', models.CharField(max_length=5)),
                ('Hg', models.CharField(max_length=5)),
                ('TSS', models.CharField(max_length=5)),
                ('NO2', models.CharField(max_length=5)),
                ('E_Coli', models.CharField(max_length=5)),
                ('SAR', models.CharField(max_length=5)),
                ('SSP', models.CharField(max_length=5)),
                ('Na_Cl_Ratio', models.CharField(max_length=5)),
                ('Cl_CO3_Ratio', models.CharField(max_length=5)),
                ('RSC', models.CharField(max_length=5)),
                ('T_Coli', models.CharField(max_length=5)),
            ],
        ),
    ]
