# Generated by Django 2.2 on 2022-03-12 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GWDapis', '0005_auto_20220305_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wells',
            fields=[
                ('registration_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('type_of_well', models.CharField(blank=True, max_length=20, null=True)),
                ('total_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WellDepth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GWDapis.Wells')),
            ],
        ),
    ]
