from django.conf import settings
from django.db import models
from django.utils import timezone

# Create your models here.
class GW_General(models.Model):
    WellNo = models.CharField(max_length=10)
    Well_Type = models.CharField(max_length=18)
    Agency = models.CharField(max_length=5)
    State = models.CharField(max_length=9)
    District = models.CharField(max_length=23)
    Block_Taluk = models.CharField(max_length=20)
    GP_Mandal = models.CharField(max_length=25)
    Village = models.CharField(max_length=25)
    Basin = models.CharField(max_length=8)
    Minor_Basin = models.CharField(max_length=15)
    Geology = models.CharField(max_length=28)
    Geomorphology = models.CharField(max_length=19)
    Toposheet_No = models.CharField(max_length=5)
    LatD = models.CharField(max_length=2)
    LatM = models.CharField(max_length=2)
    LatS = models.CharField(max_length=4)
    LonD = models.CharField(max_length=2)
    LonM = models.CharField(max_length=2)
    LonS = models.CharField(max_length=4)
    Easting = models.DecimalField(max_digits=8,decimal_places=2)
    Northing = models.DecimalField(max_digits=8, decimal_places=2)
    Method = models.CharField(max_length=9)
    Command_Area = models.CharField(max_length=5)
    MP = models.CharField(max_length=1)
    DWLR_installed = models.CharField(max_length=5)
    dwlr_no = models.CharField(max_length=8)
    DWLR_type = models.CharField(max_length=1)
    Category = models.CharField(max_length=10)
    Select = models.CharField(max_length=5)
    Filter = models.CharField(max_length=4)
    Repl = models.CharField(max_length=5)
    Urban = models.CharField(max_length=5)



class WaterLevels(models.Model):
    WellNo = models.CharField(max_length=10)
    date = models.CharField(max_length=19)
    time = models.CharField(max_length=19)
    WL_Well_Depth = models.CharField(max_length=5)
    Ht_of_Ms_Pt = models.CharField(max_length=5)
    Water_Level = models.DecimalField(max_digits=8,decimal_places=2)
    Remarks = models.CharField(max_length=5)
    Flag = models.CharField(max_length=5)
    Water_Level_MBMP = models.DecimalField(max_digits=8,decimal_places=2)


class WaterQuality(models.Model):
    WellNo  = models.CharField(max_length=10)
    SampleID  = models.IntegerField()
    SamplingDate  = models.CharField(max_length=19)
    AnalysisDate  = models.CharField(max_length=5)
    SamplingDepth  = models.CharField(max_length=5)
    LabID  = models.CharField(max_length=5)
    Colour  = models.CharField(max_length=5)
    Odour  = models.CharField(max_length=5)
    Turbidity  = models.CharField(max_length=5)
    Temp  = models.CharField(max_length=5)
    pH  = models.CharField(max_length=7)
    EC  = models.CharField(max_length=5)
    THard  = models.CharField(max_length=8)
    Alkalinity  = models.CharField(max_length=8)
    TDS  = models.CharField(max_length=7)
    CO3  = models.CharField(max_length=6)
    HCO3  = models.CharField(max_length=8)
    Cl  = models.CharField(max_length=8)
    SO4  = models.CharField(max_length=6)
    NO3  = models.CharField(max_length=10)
    Ca  = models.CharField(max_length=8)
    Mg  = models.CharField(max_length=9)
    Na  = models.CharField(max_length=8)
    K  = models.CharField(max_length=8)
    F  = models.CharField(max_length=6)
    Fe  = models.CharField(max_length=4)
    Si  = models.CharField(max_length=5)
    As  = models.CharField(max_length=5)
    Alk_Phen  = models.CharField(max_length=5)
    BOD  = models.CharField(max_length=5)
    P_Total  = models.CharField(max_length=5)
    COD  = models.CharField(max_length=5)
    DO  = models.CharField(max_length=5)
    F_Coli  = models.CharField(max_length=5)
    Pesticide  = models.CharField(max_length=5)
    PO4  = models.CharField(max_length=5)
    Pb  = models.CharField(max_length=5)
    Cr  = models.CharField(max_length=5)
    Cd  = models.CharField(max_length=5)
    Mn  = models.CharField(max_length=5)
    Ni  = models.CharField(max_length=5)
    Fe  = models.CharField(max_length=5)
    Hg  = models.CharField(max_length=5)
    TSS  = models.CharField(max_length=5)
    NO2  = models.CharField(max_length=5)
    E_Coli  = models.CharField(max_length=5)
    SAR  = models.CharField(max_length=5)
    SSP  = models.CharField(max_length=5)
    Na_Cl_Ratio  = models.CharField(max_length=5)
    Cl_CO3_Ratio  = models.CharField(max_length=5)
    RSC  = models.CharField(max_length=5)
    T_Coli  = models.CharField(max_length=5)